### ISSUE TITLE
undefined method `[]' for Geokit::GeoLoc

### ISSUE THREAD

**Issue by jhenahan** [geokit/geokit-rails#113]
I can't quite nail down what's going on with this error.

Basically, I have

```
class ApplicationController < ActionController::Base
  protect_from_forgery
  geocode_ip_address

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:show, :index, :autocomplete, :search_internal, :quickview]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [(snip)])

    devise_parameter_sanitizer.permit(:account_update,
                                      keys: [(snip)])
  end

end
```

On first loading the application, and for continuing use, everything is fine and the behavior is exactly what I want. However, if the session is invalidated (say, by logging out or by closing the browser), I get the error in the title.

In case it's relevant, I currently access the location data like so:

```
- if session[:geo_location].present?
    - location = session[:geo_location]
    - address = Geokit::Geocoders::GoogleGeocoder.reverse_geocode location
```

Or in the case that I try to check for the cookie, as well (which I tried in case that was the problem):

```
- if session[:geo_location].present? || cookies[:geo_location].present?
                - location = session[:geo_location] || cookies[:geo_location]
                - address = Geokit::Geocoders::GoogleGeocoder.reverse_geocode location
                = address.full_address
```

Am I doing something really stupid here?

Maybe a weird interaction with forgery protection or Devise?

Stack trace:

```
NoMethodError (undefined method `[]' for #<Geokit::GeoLoc:0x007f64a6bd8d48>):
  geokit (1.10.0) lib/geokit/geo_loc.rb:49:in `initialize'
  geokit-rails (2.2.0) lib/geokit-rails/ip_geocode_lookup.rb:37:in `new'
  geokit-rails (2.2.0) lib/geokit-rails/ip_geocode_lookup.rb:37:in `retrieve_location_from_cookie_or_service'
  geokit-rails (2.2.0) lib/geokit-rails/ip_geocode_lookup.rb:30:in `store_ip_location'
  activesupport (4.2.6) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.6) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  searchkick (1.4.0) lib/searchkick/logging.rb:153:in `process_action'
  activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  unicorn (5.2.0) lib/unicorn/http_server.rb:562:in `process_client'
  unicorn (5.2.0) lib/unicorn/http_server.rb:658:in `worker_loop'
  unicorn (5.2.0) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  unicorn (5.2.0) lib/unicorn/http_server.rb:132:in `start'
  unicorn-rails (2.2.1) lib/unicorn_rails.rb:33:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.6) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.6) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:9:in `require'
  bin/rails:9:in `<top (required)>'
  spring (2.0.0) lib/spring/client/rails.rb:28:in `load'
  spring (2.0.0) lib/spring/client/rails.rb:28:in `call'
  spring (2.0.0) lib/spring/client/command.rb:7:in `call'
  spring (2.0.0) lib/spring/client.rb:30:in `run'
  spring (2.0.0) bin/spring:49:in `<top (required)>'
  spring (2.0.0) lib/spring/binstub.rb:31:in `load'
  spring (2.0.0) lib/spring/binstub.rb:31:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
  bin/spring:13:in `<top (required)>'
  bin/rails:3:in `load'
  bin/rails:3:in `<main>'
```

**Comment by jamesstonehill** [comment]
I'm getting the exact same issue!

**Comment by ryankopf** [comment]
Closing as this seems to be fixed by the pull request that was merged. Feel free to create new issue if you have ongoing problems.
